// src/sections/Header.vue
<template>
  <header class="header px-4">
    <div class="row align-items-center">
      <div class="col-12 col-md-6 col-lg-9 col-xl-6 flex-grow">
        <div class="d-flex align-items-center justify-content-center justify-content-md-left" style="positon: relative">
          <mobile-drawer-icon
            :isActive="isDrawerOpen"
            @trigger="toggleDrawer"
          />
          <h1 class="p-0 m-0 py-2 pl-md-5 pl-lg-0 header_title">
            <a href="/" class="header_title_link">
              {{title}}
            </a>
          </h1>
          <mobile-drawer :isOpen="isDrawerOpen">
            <navigation @trigger="onNavigate" />
            <div class="d-block d-md-none d-flex justify-content-center py-4 py-md-none" style="position: realtive">
              <span class="mobile-line" />
              <social-list class="pt-5" />
            </div>
          </mobile-drawer>
        </div>
      </div>

      <div class="col col-xl-6 d-none d-md-flex flex-grow justify-content-right">
        <social-list />
      </div>
    </div>
  </header>
</template>

<script>
import mobileDrawer from '@/sections/MobileDrawer/MobileDrawer.vue';
import mobileDrawerIcon from '@/sections/MobileDrawer/MobileDrawerIcon.vue';
import navigation from '@/sections/Navigation.vue';
import socialList from '@/sections/SocialList.vue';

export default {
  components: {
    navigation,
    mobileDrawer,
    mobileDrawerIcon,
    socialList,
  },
  data() {
    return {
      isDrawerOpen: false,
      title: '@kroneman',
    };
  },
  methods: {
    toggleDrawer() {
      this.isDrawerOpen = !this.isDrawerOpen;
    },
    onNavigate() {
      this.isDrawerOpen = false;
    },
  },
};
</script>

<style lang="scss">
@import "./Header.scss";
.mobile-line {
  content: '';
  position: absolute;
  right: 30px;
  left: 30px;
  top: auto;
  height: 1px;
  background: rgba(theme-color(grey-3), .5);

  @include respond(lg) {
      display: none;
  }
}
</style>

// next-implementation/sections/Header/Header.tsx
import React, {useState} from 'react';

// Components
import SocialList from "../SocialList";
import Drawer, { DrawerIcon } from '../../components/Drawer'
import Navigation from '../Navigation';

// Styles
import styles from './Header.module.scss';

// Constants
const title = '@kroneman';

type HeaderProps = {
  isDrawerOpen: boolean;
}

const Header = (props: HeaderProps) => {
  const {isDrawerOpen = true} = props;
  const [drawerOpen, setDrawerOpen] = useState<boolean>(true);
  const onDrawerIconClick = () => {
    setDrawerOpen(!drawerOpen)
  };

  const onNavigate = () => {
    setDrawerOpen(false);
  }

  return (
    <header className={`${styles.header} px-4`}>
      <div className="flex items-center">
        <div className="basis-full md:basis-6/12 lg:basis-9/12 xl:basis-6/12 flex-grow">
          <div
            className="flex items-center justify-center md:justify-start relative">
            <DrawerIcon onClick={onDrawerIconClick} isActive={drawerOpen} />
            <h1 className={`p-0 m-0 py-2 md:pl-5 lg:pl-0 ${styles.header_title}`}>
              <div className="flex items-center">
                {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
                <a href="/" className={styles.header_title_link}>
                  {title}
                </a>
              </div>
            </h1>
            <Drawer isOpen={drawerOpen}>
              <Navigation onNavigate={onNavigate} />
              {/*<navigation @trigger="onNavigate" />*/}
              <div className="block md:hidden flex content-center py-4 md:py-0 relative">
                <span className="mobile-line"/>
                <SocialList className="pt-5"/>
              </div>
            </Drawer>
          </div>
        </div>

        <div className="xl:basis-6/12 hidden md:flex flex-grow justify-end">
          <SocialList/>
        </div>
      </div>
    </header>
  );
}


export default Header;
