// src/sections/Navigation.vue
<template>
  <nav class="nav">
    <ul class="nav-list">
      <li
        v-for="link in navLinks" :key="link.title"
        class="nav-list_item"
      >
        <a
          class="nav-list_link"
          :class="{
            'is-active': link.isActive
          }"
          @click="(e) => scrollTo(e, link.anchorElement)"
        >{{link.title}}</a>
      </li>
    </ul>
  </nav>
</template>

<script>
import { debounce, isInViewport } from '@/utils';

export default {
  name: 'Navigation',
  data() {
    return {
      navLinks: [
        {
          anchor: '#Projects',
          title: 'Projects',
          isActive: false,
          anchorLocation: null,
          anchorElement: null,
        },
        {
          anchor: '#Experience',
          title: 'Experience',
          isActive: false,
          anchorLocation: null,
          anchorElement: null,
        },
        {
          anchor: '#Tech',
          title: 'Tech',
          isActive: false,
          anchorLocation: null,
          anchorElement: null,
        },
        {
          anchor: '#About',
          title: 'About',
          isActive: false,
          anchorLocation: null,
          anchorElement: null,
        },
        {
          anchor: '#Contact',
          title: 'Contact',
          isActive: false,
          anchorLocation: null,
          anchorElement: null,
        },
      ],
    };
  },
  mounted() {
    this.$nextTick(() => {
      this.navLinks = this.navLinks.map(this.getAnchorElements);
      this.getAnchorLocations();
      this.onScroll();
      window.addEventListener('scroll', this.onScroll);
      window.addEventListener('resize', this.getAnchorLocations);
    });
  },
  methods: {
    scrollTo(e, anchorElement) {
      const distanceToTop = (el) => Math.floor(el.getBoundingClientRect().top);
      e.preventDefault();
      if (!anchorElement) {
        return;
      }

      const originalTop = distanceToTop(anchorElement);
      window.scrollBy({ top: originalTop, left: 0, behavior: 'smooth' });
    },
    onScroll() {
      const updatedAnchorElements = this.navLinks.map((navLink) => {
        const isActive = navLink.anchorElement ? isInViewport(navLink.anchorElement, 500) : false;
        return {
          ...navLink,
          isActive,
        };
      });

      this.navLinks = updatedAnchorElements;
    },
    getAnchorElements(navLink) {
      const anchorElement = document.querySelector(navLink.anchor);
      return {
        ...navLink,
        anchorElement,
      };
    },
    getAnchorLocations: debounce(function getAnchorLocations() {
      this.navLinks = this.navLinks.map((navLink) => {
        if (!navLink.anchorElement) {
          return navLink;
        }

        const anchorLocation = Math.floor(navLink.anchorElement.getBoundingClientRect().top);
        return {
          ...navLink,
          anchorLocation: anchorLocation || null,
        };
      }).filter((item) => Boolean(item.anchorElement));
    }, 100),
  },
};
</script>

<style lang="scss">
@import "./Navigation.scss";
</style>

// next-implementation/sections/Navigation/Navigation.tsx
import React, {useEffect, useState} from 'react';
import styles from './Navigation.module.scss';
import {debounce, isInViewport, throttle} from "../../utils";

type INavLink = {
  anchor: string;
  title: string;
  isActive: boolean;
  anchorLocation: null | number,
  anchorElement: null | Element,
}

type NavigationProps = {
  onNavigate: () => void
}

const Navigation = (props: NavigationProps) => {
  const { onNavigate } = props;
  const [isLoading, setIsLoading] = useState(true);
  const [navLinks, setNavLinks] = useState<INavLink[]>(links);

  const getLinkClassName = (isActive: boolean) => {
    return [
      styles.nav_list_link,
      isActive ? styles.is_active : null
    ].filter(Boolean).join(' ');
  }

  const scrollTo = (e: React.MouseEvent<HTMLAnchorElement>, anchorElement: HTMLElement) => {
    onNavigate();
    const distanceToTop = (el: HTMLElement) => Math.floor(el.getBoundingClientRect().top);
    e.preventDefault();
    if (!anchorElement) {
      return;
    }

    const originalTop = distanceToTop(anchorElement);
    window.scrollBy({ top: originalTop, left: 0, behavior: 'smooth' });
  }

  const onClickItem = (e: React.MouseEvent<HTMLAnchorElement>, anchorElement: any) => {
    scrollTo(e, anchorElement);
  }

  const getAnchorElements = (navLinkMap: INavLink) => {
    const anchorElement = document.querySelector(navLinkMap.anchor);
    return {
      ...navLinkMap,
      anchorElement,
    };
  }

  const getAnchorLocations = debounce(function getLocations() {
    const withAnchorLocations = navLinks.map((link) => {
      if(!link.anchorElement) {
        return link;
      }

      const anchorLocation = Math.floor(link.anchorElement.getBoundingClientRect().top);
      return {
        ...link,
        anchorLocation: anchorLocation || null,
      };
    })
      // .filter((item) => Boolean(item.anchorElement));

    setNavLinks(withAnchorLocations);
    setIsLoading(false);
  }, 100);

  const onScrollHandler = throttle(function onScroll() {
    const updatedAnchorElements = navLinks.map((link) => {
      const isActive = link.anchorElement ? isInViewport(link.anchorElement, 500) : false;
      return {
        ...link,
        isActive,
      };
    });

    setNavLinks(updatedAnchorElements);
  }, 100)

  useEffect(() => {
    const withAnchorElements = navLinks.map(getAnchorElements);
    setNavLinks(withAnchorElements);
  }, []);

  useEffect(() => {
    if(!navLinks) {
      return;
    }

    getAnchorLocations();
  }, [navLinks]);

  useEffect(() => {
    onScrollHandler();

    window.addEventListener('scroll', onScrollHandler);
    window.addEventListener('resize', getAnchorLocations);

    // Cleanup during un-mount
    return () => {
      window.removeEventListener('scroll', onScrollHandler);
      window.removeEventListener('resize', getAnchorLocations);
    };
  }, [isLoading]);

  return (
    <nav className={styles.nav}>
      <ul className={styles.nav_list}>
        {navLinks && navLinks.map((link, index) => (
          <li key={index} className={styles.nav_list_item}>
            <a onClick={(e) => onClickItem(e, link.anchorElement)}
               className={getLinkClassName(link.isActive)}>{link.title}</a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

const links = [
  {
    anchor: '#Projects',
    title: 'Projects',
    isActive: false,
    anchorLocation: null,
    anchorElement: null,
  },
  {
    anchor: '#Experience',
    title: 'Experience',
    isActive: false,
    anchorLocation: null,
    anchorElement: null,
  },
  {
    anchor: '#Tech',
    title: 'Tech',
    isActive: false,
    anchorLocation: null,
    anchorElement: null,
  },
  {
    anchor: '#About',
    title: 'About',
    isActive: false,
    anchorLocation: null,
    anchorElement: null,
  },
  {
    anchor: '#Contact',
    title: 'Contact',
    isActive: false,
    anchorLocation: null,
    anchorElement: null,
  }
];

export default Navigation;
