// src/components/card/card.vue
<template>
  <div class="card">
    <div class="card_image">
      <img v-if="image" :src="image" />
      <icon v-if="icon" :name="icon" class="full-size" />
    </div>
    <div class="card_text p-4">
      <h4 class="my-1">{{title}}</h4>
      <p class="fs-16 fs-md-18">{{text}}</p>
      <link-custom class="fs-18" :href="link" :external="linkExternal">
        <span v-if="linkText">
          {{linkText}}
        </span>
        <span v-else>
          {{link}}
        </span>
      </link-custom>
    </div>
  </div>
</template>

<script>
import Icon from '@/components/icon/icon.vue';
import linkCustom from '@/components/link-custom/link-custom.vue';

export default {
  name: 'Card',
  components: {
    Icon,
    linkCustom,
  },
  props: {
    image: {
      type: String,
      required: false,
      default: null,
    },
    icon: {
      type: String,
      required: false,
      default: null,
    },
    title: {
      type: String,
      required: false,
      default: null,
    },
    text: {
      type: String,
      required: false,
      default: null,
    },
    link: {
      type: String,
      required: false,
      default: null,
    },
    linkExternal: {
      type: Boolean,
      required: false,
      default: false,
    },
    linkText: {
      type: String,
      required: false,
      default: null,
    },
  },
};
</script>

<style lang="scss">
@import "./card";
</style>

// next-implementation/components/Card/Card.tsx
import React from 'react';

// Types
import {IconName} from "../Icon/Icon";

// Components
import Icon from "../Icon";
import Image from 'next/image';

// Styles
import styles from './Card.module.scss';
import CustomLink from "../CustomLink";

type CardProps = {
  image?: string;
  icon?: IconName;
  title?: string;
  text?: string;
  link: string;
  linkExternal?: boolean
  linkText?: string
} & React.ComponentProps<any>;

const Card = (props: CardProps) => {
  const {
    image = null,
    icon = null,
    title = null,
    text = null,
    link,
    linkExternal = false,
    linkText = null,
    className
  } = props;

  const cardWrapperStyles = [
    styles.card,
    className
  ].filter(Boolean).join(' ')

  return (
    <div className={cardWrapperStyles}>
      <div className={styles.card_image}>
        {image ? <Image width={477} height={233} layout="responsive" src={image} alt="" /> : null}
        {icon ? (
          <div className="absolute top-0 left-0 right-0 bottom-0 w-full h-full flex justify-center">
            <Icon name={icon} className={styles.card_icon} />
          </div>
        ): null}
      </div>
      <div className={`${styles.card_text} p-4`}>
        <h4 className="my-1">{title}</h4>
        <p className="fs-16 md:fs-18">{text}</p>
        <CustomLink href={link} className="fs-18" external={linkExternal}>
          {linkText
            ? (<span>{linkText}</span>)
            : (<span>{link}</span>)
          }
        </CustomLink>
      </div>
    </div>
  );
}

export default Card;
